services:
  - type: web
    name: flextype
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js || node server.js
    envVars:
      - key: NODE_ENV
        value: production