services:
  - type: web
    name: flextype
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Render automatically sets PORT, so we don't need to specify it here